print "Hello World!"
print "Hello Again"
print "I like typing this"
print "this is fun"
print "yay! printing"
print "I'd much rather 'not'"
print "I ""said"" do not touch this"  
print "Testing my memmory"